spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: admin
    password: admin
    #druid
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
    # 配置获取连接等待超时的时间
      max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/views/
server:
  port: 8000
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
logging:
  level:
    com.sb.sbdemo.dao: debug
#  params: count=countSql